version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ezyCare_backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5050:5050"